### ISSUE TITLE
Inferenece for different target densities

### ISSUE THREAD

**Issue by kainat-altaf-cau** [lfr-0531/DGNet#10]
Hello,

My question is do you train a separate model for each target density(50%, 70%)? If yes, how is it dynamic during inference? 

Thank You.

**Comment by lfr-0531** [comment]
Yes, we need to train different models with different target sparse ratios.
As for the dynamic property, it means that with the same sparse ratio, for different input samples, the model will have different sparse patterns. In this way, we can get better model accuracy.
