### ISSUE TITLE
Applying Only Channel Gating

### ISSUE THREAD

**Issue by rayush7** [lfr-0531/DGNet#4]
Hi,

Thanks for the code of your work.

Could you please suggest how can I perform the ablation study of applying only channel gating. I commented out all the lines [here](https://github.com/lfr-0531/DGNet/blob/main/models/imagenet/resdg.py#L44) but I am getting constant ratio of real flops and ori flops despite setting the target density between 0.3 to 0.7. I am unable to understand if I am making any errors regarding this. Please help.

Thanks

**Comment by lfr-0531** [comment]
You can first remove all modules and variables related to the spatial mask in the model, and then modify the FLOSs statistics in the model and the losses in [regularization.py](https://github.com/lfr-0531/DGNet/blob/main/regularization.py).

**Comment by rayush7** [comment]
Thank you.
