### ISSUE TITLE
target budget in bound loss

### ISSUE THREAD

**Issue by Yu-Zhewen** [lfr-0531/DGNet#5]
Dear authors, thank you for sharing this excellent work!

I wonder why the target budget is set as sqrt(T_d) rather than T_d. In https://arxiv.org/abs/1912.03203, which you also refer to in your paper, the target budget was set as T_d.

Could you please explain a bit more about this design choice? Thanks

**Comment by lfr-0531** [comment]
The sparsities come from both the spatial and channel dimensions, and we want the target ratio of the average FLOPs to reach T_d. So we set the target budget as sqrt(T_d) for both the two dimensions.

**Comment by Yu-Zhewen** [comment]
Thanks! That's very helpful.
