### ISSUE TITLE
About cifar10 baseline

### ISSUE THREAD

**Issue by CheungBH** [lfr-0531/DGNet#6]
Hello. Thanks for your great work. 
I noticed that in your paper you mentioned you obtain a good performance in cifar10 baseline. I wonder could we access the baseline checkpoints? They are not available in your folder downloaded from google.
<img width="565" alt="Screenshot 2022-08-01 at 10 07 08" src="https://user-images.githubusercontent.com/39186017/182058765-add36652-2e61-4937-af2b-d933e15d0a46.png">

**Comment by lfr-0531** [comment]
The pre-trained cifar10 models can be found here: [Google Drive](https://drive.google.com/file/d/15sM2W2ADqtq5Gr8RTdaFalPK7qIw0VXF/view?usp=sharing). We have added it to the README.
