### ISSUE TITLE
Speedup in Table 3

### ISSUE THREAD

**Issue by Lutong-Qin** [lfr-0531/DGNet#7]
![image](https://user-images.githubusercontent.com/51037385/192094024-e954cea4-f3b3-45a1-87f6-07cad876bf98.png)
Thank you for your excellent work. I sincerely want to ask you:

1. What is the unit of Speedup in Table 3, milliseconds?

2. Is there a specific baseline and new network running time?
I hope to get your answers. I would appreciate it

**Comment by lfr-0531** [comment]
1. Speedup = Baseline time / DGNet time
2. Res-18 Baseline time = 63.4436 ms
    Res-18 DGNet (60%) time  = 51.0329 ms
    Res-34 Baseline time = 112.1767 ms
    Res-34 DGNet (60%) time = 92.4704 ms
    Res-34 DGNet (70%) time = 79.7277 ms
