### ISSUE TITLE
A question about speed measurement

### ISSUE THREAD

**Issue by Lutong-Qin** [lfr-0531/DGNet#8]
Hello, I'm sorry to bother you,I'd like to ask you some questions,your paper says that it can actually accelerate CPU, could you tell me how to accelerate it in detail? The speed measured by me is nearly twice full, thank you very much for your answer.
![image](https://user-images.githubusercontent.com/51037385/201083192-e76128bb-c0b1-4973-a92b-679e828d522d.png)

**Comment by lfr-0531** [comment]
We actually modified the implementation of convolution in PyTorch. The sparse convolution in DGNet can be implemented with a smaller GEMM, and this can save running time.
